version: 0.2

phases:
  install:
    commands:
      - echo Install python modules for this build...
      - pip install pytest aws-sam-cli

  pre_build:
    commands:
      - echo Run unit test...
      - echo to be updated...
      - echo Validate template.yaml...
      - sam validate

  build:
    commands:
      - echo Install requirements for app...
      - pip install -r requirements.txt -t apidemo/build/
      - cp apidemo/*.py apidemo/build/
      - echo Gen packaged.yaml...
      - bash build.sh

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
    files: packaged.yaml